my_project/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6.urls'), name='index')
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<str:pk>', views.delete_event, name='delete_event'),
    path('delete/member/<str:pk>', views.delete_member, name='delete_member'),
]

story6/models.py
from django.db import models


class Event(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Member(models.Model):
    name = models.CharField(max_length=100)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

story6/forms.py
from django import forms

from .models import Event, Member


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "What's your next plan?"
            }),
        }


class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Who's joining?"
            }),
        }

story6/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from .forms import EventForm, MemberForm
from .models import Event, Member


def index(request):
    if request.method == "POST":
        event_form = EventForm(request.POST)
        member_form = MemberForm(request.POST)
        if event_form.is_valid():
            event_form.save()
            messages.success(request, (f"{request.POST['title']} event added."))
            return redirect('story6:index')
        elif member_form.is_valid():
            member_form.save()
            messages.success(request, (f"Participant named {request.POST['name']} added."))
            return redirect('story6:index')
        else:
            messages.error(request, (f"Invalid input!"))
            return redirect('story6:index')
    else:
        event_form = EventForm()
        member_form = MemberForm()
        events = Event.objects.all()
        members = Member.objects.all()
        is_empty = False
        if not events:
            is_empty = True
        context = {
            'event_form': event_form,
            'member_form': member_form,
            'events': events,
            'members': members,
            'is_empty': is_empty,
        }
        return render(request, 'story6/index.html', context)


def delete_event(request, pk):
    event = Event.objects.get(id=pk)
    event.delete()
    messages.warning(request, (f"{event} event deleted."))
    return redirect('story6:index')


def delete_member(request, pk):
    member = Member.objects.get(id=pk)
    member.delete()
    messages.warning(request, (f"Participant named {member} deleted."))
    return redirect('story6:index')

story6/templates/story6/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Primary Meta Tags -->
  <title>EO CEO</title>
  <meta name="title" content="EO CEO">
  <meta name="description" content="An event organizer which is also a bug repellent!">

  <!-- Open Graph / Facebook -->
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://jojostory6.herokuapp.com/">
  <meta property="og:title" content="EO CEO">
  <meta property="og:description" content="An event organizer which is also a bug repellent!">
  
  <!-- Bootstrap CSS and Scripts -->
  <link rel="stylesheet" href="{% static 'story6/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light navbar-custom justify-content-between">
    <a class="navbar-brand" href="/">EO CEO</a>
  </nav>

  {% block content %}
  {% endblock %}

  <footer class="page-footer font-small fixed-bottom">
    <div class="footer-copyright text-center py-3">
      Made by Jojo, 2020
    </div>
  </footer>
</body>
</html>

story6/templates/story6/index.html
{% extends 'story6/base.html' %}
{% load static %}
{% block content %}
<div class="container py-4">
  <form method="POST" class="row my-3">
    {% csrf_token %}
    <div class="col-7 ml-auto">
      {{ event_form.title }}
    </div>
    <button type="submit" class="btn btn-primary col-2 mr-auto">Add Event</button>
  </form>

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}

  <div class="d-flex justify-content-around flex-wrap pb-4">
    {% for event in events %}
      <div class="card bg-light mt-5" style="width: 18rem;">
        <div class="card-header">
          <div class="row">
            <h5 class="col-10 mb-2">{{ event.title }}</h5>
            <a href="{% url 'story6:delete_event' event.id %}" class="col-2">
              <button type="button" class="close mb-2">&times;</button>
            </a>
          </div>
        </div>

        <div class="card-body">
          <h6 class="card-title">Participants:</h6>
          <p></p>
          {% for member in members %}
            {% if member.event.id == event.id %}
              <div class="row">
                <h5 class="col-10 text-left">{{ member.name }}</h5>
                <a href="{% url 'story6:delete_member' member.id %}" class="col-2">
                  <button type="button" class="close">&times;</button>
                </a>    
              </div>
            {% endif %}
          {% endfor %}
          <form method="POST">
            {% csrf_token %}
            {{ member_form.name }}
            <input name="event" type="text" value="{{ event.id }}" style="display: none;">
            <button type="submit" class="btn btn-primary col-3 mt-3 mx-auto">Join</button>
          </form>
        </div>
      </div>
    {% endfor %}
  </div>
  {% if is_empty %}
    <div class="container d-flex h-100">
      <div class="row align-self-center w-100">
        <div class="col-lg-4 col-md-6 col-sm-6 mx-auto">
          <div class="container" align="center">
            <img src="{% static 'story6/images/kanata.png' %}" class="img-fluid" alt="PPT" id="kanata">
            <h3>Event Empty</h3>
            <p class="lead">Add an event and it will show up here.</p>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
</div>
{% endblock content %}